### ISSUE TITLE
What server should I use?

### ISSUE THREAD

**Issue by UnRealm** [xAzz/AthexClient#10]
Hi,
I'm using MultiOgarII server. https://github.com/m-byte918/MultiOgarII
It works.
But I can't use it with this client.
What Agario server is recommended for this client? @xAzz 

At the moment when I click "Play" I see just background.
![](https://i.imgur.com/cyd8TG4.png)

**Comment by xAzz** [comment]
Are you initiating the connection to your MultiOgar server?

**Comment by xAzz** [comment]
Also, I'm not sure of MultiOgarII, I used MultiOgar-Edited on this client.
