### ISSUE TITLE
Chat and Skins

### ISSUE THREAD

**Issue by cowpits** [xAzz/AthexClient#3]
Is there a Chat and Skins server included? I got minimap server working but don't see an option to start Chat and Skins.

**Comment by xAzz** [comment]
Thats included in the minimap server in the socket directory

**Comment by cowpits** [comment]
yes I got minimap working but there's no way I can type in chat. I have the pre-defined chats only. The chat box doesn't allow any input.

**Comment by xAzz** [comment]
Hm I'll have a look, once I get net back I'll upload a fixed version

**Comment by cowpits** [comment]
very nice, thank you so much.

**Comment by cowpits** [comment]
if you want to see what i'm talking about, i have it here as a test http://cowpits.0fees.us/cowpits/?i=1

**Comment by xAzz** [comment]
Ok yeah. I think I fucked up the hotkey or something, I'll look into it now

**Comment by xAzz** [comment]
Haha, I fixed it. It was HTML mistake. Will upload new index now.
