### ISSUE TITLE
How to change players nickname color in cell for certain ip?

### ISSUE THREAD

**Issue by NiroxyNation** [xAzz/AthexClient#4]
I have been trying to do this all week and cannot find a way of doing this can you help me please? i want it to look something like this in the image:
![image](https://user-images.githubusercontent.com/38017625/38214945-0a597c14-36be-11e8-93e1-3909c0b4f5f4.png)

**Comment by NiroxyNation** [comment]
@xAzz

**Comment by xAzz** [comment]
I haven't added that, this project barely gets updated.

**Comment by NiroxyNation** [comment]
Is there a code you have for colored names for certain names?

**Comment by NiroxyNation** [comment]
@xAzz

**Comment by xAzz** [comment]
My colored names is in a json file and is only for leaderboard color.

**Comment by NiroxyNation** [comment]
Thank you bro

**Comment by NiroxyNation** [comment]
They arent working @xAzz idk why can u try to fix please!

**Comment by xAzz** [comment]
Can you explain what is not working?

**Comment by NiroxyNation** [comment]
![image](https://user-images.githubusercontent.com/38017625/38702220-f1c9c85c-3e97-11e8-8167-e01f83e8e05d.png)

**Comment by NiroxyNation** [comment]
Have i done it correctly? @xAzz Because when i save it and try to use the name it doesnt work

**Comment by Shair17** [comment]
@NiroxyNation Delete "//"
you can't add that in this json file.
